// export const metadata = {
//   title: 'Next.js',
//   description: 'Generated by Next.js',
// }

import Head from "next/head";
import Navbar from "../components/Navbar";

// export default function RootLayout({ children }) {
//  return (
//     <html lang="en">
//       <body>{children}</body>
//     </html>
//   )
// }

export default function RootLayout({ children }) {
  return (
    <html>
      <body>
        <Navbar />
        mi pagina
        {children}
      </body>
    </html>
  );
}
